/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as AppUserImport } from './routes/_app/user'
import { Route as AppConnectionNewImport } from './routes/_app/connection/new'
import { Route as AppConnectionConnectionIdImport } from './routes/_app/connection/$connectionId'
import { Route as AppChatConversationIdImport } from './routes/_app/chat/$conversationId'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppUserRoute = AppUserImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AppRoute,
} as any)

const AppConnectionNewRoute = AppConnectionNewImport.update({
  id: '/connection/new',
  path: '/connection/new',
  getParentRoute: () => AppRoute,
} as any)

const AppConnectionConnectionIdRoute = AppConnectionConnectionIdImport.update({
  id: '/connection/$connectionId',
  path: '/connection/$connectionId',
  getParentRoute: () => AppRoute,
} as any)

const AppChatConversationIdRoute = AppChatConversationIdImport.update({
  id: '/chat/$conversationId',
  path: '/chat/$conversationId',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/user': {
      id: '/_app/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AppUserImport
      parentRoute: typeof AppImport
    }
    '/_app/chat/$conversationId': {
      id: '/_app/chat/$conversationId'
      path: '/chat/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof AppChatConversationIdImport
      parentRoute: typeof AppImport
    }
    '/_app/connection/$connectionId': {
      id: '/_app/connection/$connectionId'
      path: '/connection/$connectionId'
      fullPath: '/connection/$connectionId'
      preLoaderRoute: typeof AppConnectionConnectionIdImport
      parentRoute: typeof AppImport
    }
    '/_app/connection/new': {
      id: '/_app/connection/new'
      path: '/connection/new'
      fullPath: '/connection/new'
      preLoaderRoute: typeof AppConnectionNewImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppUserRoute: typeof AppUserRoute
  AppChatConversationIdRoute: typeof AppChatConversationIdRoute
  AppConnectionConnectionIdRoute: typeof AppConnectionConnectionIdRoute
  AppConnectionNewRoute: typeof AppConnectionNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppUserRoute: AppUserRoute,
  AppChatConversationIdRoute: AppChatConversationIdRoute,
  AppConnectionConnectionIdRoute: AppConnectionConnectionIdRoute,
  AppConnectionNewRoute: AppConnectionNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/user': typeof AppUserRoute
  '/chat/$conversationId': typeof AppChatConversationIdRoute
  '/connection/$connectionId': typeof AppConnectionConnectionIdRoute
  '/connection/new': typeof AppConnectionNewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/user': typeof AppUserRoute
  '/chat/$conversationId': typeof AppChatConversationIdRoute
  '/connection/$connectionId': typeof AppConnectionConnectionIdRoute
  '/connection/new': typeof AppConnectionNewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/user': typeof AppUserRoute
  '/_app/chat/$conversationId': typeof AppChatConversationIdRoute
  '/_app/connection/$connectionId': typeof AppConnectionConnectionIdRoute
  '/_app/connection/new': typeof AppConnectionNewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/user'
    | '/chat/$conversationId'
    | '/connection/$connectionId'
    | '/connection/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/user'
    | '/chat/$conversationId'
    | '/connection/$connectionId'
    | '/connection/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/user'
    | '/_app/chat/$conversationId'
    | '/_app/connection/$connectionId'
    | '/_app/connection/new'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/user",
        "/_app/chat/$conversationId",
        "/_app/connection/$connectionId",
        "/_app/connection/new"
      ]
    },
    "/_app/user": {
      "filePath": "_app/user.tsx",
      "parent": "/_app"
    },
    "/_app/chat/$conversationId": {
      "filePath": "_app/chat/$conversationId.tsx",
      "parent": "/_app"
    },
    "/_app/connection/$connectionId": {
      "filePath": "_app/connection/$connectionId.tsx",
      "parent": "/_app"
    },
    "/_app/connection/new": {
      "filePath": "_app/connection/new.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
